### ISSUE TITLE
Unclear Use Case

### ISSUE THREAD

**Issue by Salamandastron1** [locuslab/chatllm-vscode#12]
I thought this would be like a code linter and recommendation engine, eg Github Copilot.

But its just an integration with ChatGPTs chat client. Why would I use this over Tabnine or Copilot (beyond paying because this doesn't even do what they do)?

**Comment by zkolter** [comment]
This ... isn't those things?  The README makes this pretty clear, no?  This is a integration for long-form chats via the VSCdoe notebook interface, which is (for some, including myself) a much nicer format that other chat interfaces.  If you want other functionality, you should just use those tools.
